name: Check and build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ENVIRONMENT: dev

jobs:
  webapp_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
